DROP TABLE if EXISTS board;
CREATE TABLE board(
	hit BIGINT,
	NO BIGINT NOT NULL AUTO_INCREMENT,
	update_date DATETIME(6),
	writed_date DATETIME(6),
	writer VARCHAR(30) NOT NULL,
	title VARCHAR(300) NOT NULL,
	content TEXT NOT NULL,
	pw VARCHAR(255) NOT NULL,
	PRIMARY KEY(NO)
) ENGINE=INNODB;